# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='last_upadted',
            new_name='last_updated',
        ),
    ]
