# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20180417_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='fileLocation',
            field=models.CharField(default='empty', max_length=200),
            preserve_default=False,
        ),
    ]
